app = "reinart-portfolio"

[build]
  builder = "heroku/buildpacks:20"

[env]
  HOST = "0.0.0.0"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443